### DISCUSSION TITLE
Outgoing Webhooks

### DISCUSSION THREAD

**Discussion by USBWAG** [ptarmiganlabs/butler#1040] [Q&A] [answered]
Hello everyone

Have any of you tried outbound webhooks?

I'm currently working on version 9.4.0 and 11.0.2 for testing purposes, both of which are running without any problems, but now that I'm configuring the webhooks I'm running into problems

Locally I'm developing a python backend that should receive the PUT / GET /PUSH events, and it works so far

![image](https://github.com/ptarmiganlabs/butler/assets/86729881/f12cb42a-53f6-4d40-90da-1db26f17f4e6)

Can i only define 1 webhook? So, for example, only POST? Without GET and PUT? I haven't been able to do it at the moment

Locally it is only HTTP development, and when I try to send on an https connection I encounter errors.

Do the outgoing webhooks only support http destinations?
And which certificates is he trying to verify for the https interface?
![image](https://github.com/ptarmiganlabs/butler/assets/86729881/f8a55854-db1d-41d4-907e-758fb1b1ced5)

The behavior of the whole thing is the same on both versions.

**Comment by USBWAG** [comment]
Hello everyone,
It's done, unfortunately I had to specify this variable on the server where Butler is running that it can send on HTTPS
NODE_TLS_REJECT_UNAUTHORIZED = 0
Otherwise I could not put the whole thing into operation.

Therefore my question to the users, do you always need 3 "webhooks" or would one kind not be enough?
Would it make sense to extend the whole thing with HTTPS authentication? (SSL Certs)
Or would a header authentication be better?
What do you think?

And would then directly simplify an adjustment of the config file in this syntax with the approach here

webhookNotification:
  enable: true
  reloadTaskFailure: true
  reloadTaskAborted: true
  serviceMonitor: true
  httpmethods:
    POST: true
    PUT: true
    GET: true
  baseURL: "https://thebutlerbackend.com/"
  ssl: true
  certfile: "/path/to/your/certificate.crt"
  keyfile: "/path/to/your/private_key.key"
  webhooks:
    - description: 'This is The Outgoing POST notification'
      path: "/BUTLER_POST"
    - description: 'This is The Outgoing PUT notification'
      path: "/BUTLER_PUT"
    - description: 'This is The Outgoing GET notification'
      path: "/BUTLER_GET"

What do you think?

I would also like to support the Refactor part of the Webhook's if you like

**Reply by mountaindude** [reply]
Hey, thanks for your insights and feedback.

The very latest Butler uses a newer Node.js version, which changed some things around TLS certificates. That could be (part of) the reason you are seeing this. 
Or... the webhook code in Butler is pretty old and to be honest I am not sure it's verified to work with https webhooks. Need to check that.


Re your question about whether 3 webhooks are always needed the answer is no.
The reason they are there in the template config file is simply to show that it's possible to use either of POST, PUT and GET methods in the outgoing webhook. 
You can have 1 GET hook, or 5 POST hooks. Or any combination.

I'll look into the TLS part. 
If nothing else it should be possible to state that self-signed certificates should be allowed. Should also be possible to enable/disable the individual hook types (for reload failed/aborted, service monitoring etc).

**Reply by mountaindude** [reply]
@USBWAG 

I took a look at Butler's code for outgoing webhooks, and my suspicion was correct:
That code was created long ago for a use-case where TLS (i.e. https) was not needed.
There is no handling of self-signed certificates, ignoring certificate errors or similar.
That explains why things worked when you  set `NODE_TLS_REJECT_UNAUTHORIZED = 0` on the server where Butler is running.

Adding support for self-signed certificates to outgoing webhooks is certainly possible, but won't happen overnight, I am afraid. 
Hard to give an exact date, but realistically I'd say a few weeks. 

The work that needs to be done is more or less:

- Add entries to the YAML config file to handle custom certificates that should be used when doing outgoing webhook calls
- Add the new entries to the [config file verification/assert code](https://github.com/ptarmiganlabs/butler/blob/master/src/lib/assert/assert_config_file.js).
- Add code to use those certificates if they are enabled in the config file


For reference, most of the webhook related code is found [here](https://github.com/ptarmiganlabs/butler/blob/master/src/lib/webhook_notification.js).

**Comment by mountaindude** [comment]
@USBWAG By the way, I realised that the docs at butler.ptarmiganlabs.com are not very complete when it comes to describing possible destinations for reload failure/aborted alerts.

FYI, I created a ticket to track this: https://github.com/ptarmiganlabs/butler/issues/1078

**Comment by mountaindude** [comment]
Alright, I am thinking along these lines for adding support for outgoing webhooks calls to handle self-signed certificates in a good way.

- You can use https already today if the https server uses a proper certificate that is backed by a public CA. Just use `https` and things should work.
- If using self-signed certificates on the server the webhook will call, Butler must be told about that certificate's CA. Otherwise there will be a certificate warning.
- Add an option for disregarding certificate warnings. Useful during testing, for example.

As different outgoing webhooks may have their own requirements with respect to certificates etc, it makes sense to use separate cert configs for each webhook.

That would give us something like this in the config file:


```yaml
  # Settings for notifications and messages sent using outgoing webhook
  webhookNotification:
    enable: true
    reloadTaskFailure:
      rateLimit: 15                   # Min seconds between outgoing webhook calls for a given taskID. Defaults to 5 minutes.
      webhooks:
        - description: 'This outgoing webhook is used to...'
          webhookURL: https://10.11.12.13:8765/butler_get              # outgoing webhook that Butler will call
          httpMethod: GET                   # GET/POST/PUT. 
          cert:
            enable: true                    # Set to true to use a custom CA certificate when calling the webhookURL
            rejectUnauthorized: true       # Set to false to ignore warnings/errors caused by self-signed certificates used on the webhooks server.
            certCA: /path/to/ca-cert.pem       # Path to the CA certificate file
```
