### DISCUSSION TITLE
Add more control over which users will never have their access licenses released

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler#1097] [Ideas]
Currently (v12.1) it is possible to state specific users (in the config file) that will be excluded from license releases.

Would be useful to expand this with additional filters/criteria. 
For example, never release users...

- that are tagged with a certain tag
- that has a custom property set to a certain value
- that reside in a certain user directory
- that are active (=not active). I.e. users with QMC column `Inactive` set to `No`
- that are not blocked. I.e. users with QMC column `Blocked` set to `No`
- that are not removed externally. I.e. users with QMC column `Removed externally` set to `No`

Also add a dry-run option. When set to true, information about licenses releases would be written to the log, but no releases would actually be done. Useful when testing and refining the license release configuration.

The config settings for this could look like below. 
Note that this would be a change from current config file format.

```yaml
Butler:
  ...
  ...
  # Settings for monitoring Qlik Sense licenses
  qlikSenseLicense:
    ...
    ...
    licenseRelease:
      enable: true 
      dryRun: true               # true/false. If true, Butler will not actually release any licenses, just log what it would have done. 
                                 # Useful when refining license release settings.
      frequency: every 2 days
      neverRelease:
        user:                         # Users who should never have their licenses released
          - userDir: 'MYDIR'
            userId: 'qlikserviceaccount'
          - userDir: 'MYDIR'
            userId: 'joe'
        tag:                          # Users with these tags will never have their licenses released
          - License do not release
          - some other tag
        customProperty:               # Users with these custom properties will never have their licenses released
          - name: LicenseManage
            value: do-not-release
        userDirectory:                # List of user directories whose users should never have their licenses released
          - INTERNAL
          - ADMIN
        inactive: Ignore              # Ignore/Yes/No, No = Don't release licenses for users marked as "Inactive=No" in the QMC
                                      #                Yes = Don't release licenses for users marked as "Inactive=Yes" in the QMC 
                                      #                Ignore = Disregard this setting
                                      #                The value in this setting is case insensitive
        blocked: Ignore               # Ignore/Yes/No, No = Don't release licenses for users marked as "Blocked=No" in the QMC
        removedExternally: ignore     # Ignore/Yes/No, No = Don't release licenses for users marked as "Removed externally=No" in the QMC
      licenseType:                    # License types to monitor and release
        analyzer:                     
          enable: true
          releaseThresholdDays: 30
        professional:
          enable: true
          releaseThresholdDays: 30
      destination:
        influxDb:                     # Store info about released licenses in InfluxDB
          enable: true
          tag: 
            static:                   # Static attributes/tags to attach to the data sent to InflixDB
              - name: foo
                value: bar
```
