### DISCUSSION TITLE
SOLVED: Config Error

### DISCUSSION THREAD

**Discussion by khimhoe** [ptarmiganlabs/butler#1141] [General]
I tried to start Butler, but I'm getting the following error:

```
2024-05-08T01:38:42.883Z error: CONFIG: Getting host info: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received type number (137340747776)
2024-05-08T01:38:43.482Z verbose: Running as standalone app: true
2024-05-08T01:38:43.484Z verbose: New Relic account names/API keys/account IDs (via command line or config file): [
  {
    "accountName": "First NR account",
    "insertApiKey": "<API key 1 (with insert permissions) from New Relic>",
    "accountId": "<New Relic account ID 1>"
  },
  {
    "accountName": "Second NR account",
    "insertApiKey": "<API key 2 (with insert permissions) from New Relic>",
    "accountId": "<New Relic account ID 2>"
  }
]
2024-05-08T01:38:43.484Z debug: CONFIG: API doc mode=off
2024-05-08T01:38:43.488Z info: Enabled API endpoints: []
```

I'm not using New Relic. I tried to put some dummy value in it and also tried removing the value in the ApriKey and Account ID, but it doesn't work.

Running on Windows standalone exe. Butler version 12.3.0.

**Comment by mountaindude** [comment]
Happy to help if I can.

In order to help I need to know a) what command (incl command line options etc) you used to start Butler, and b) what the config file looks like. 

You may want to do a find-replace of sensitive info (ip addresses, account names  etc) in the config file before posting it here.
Or email it to me if you are comfortable doing that, goran -at- ptarmiganlabs -dot- com.

The config file is somewhat of a beast, but things tend to work out if you scale it down to only include the essentials.

**Comment by mountaindude** [comment]
@khimhoe 

Check out the just released version [12.4.0](https://github.com/ptarmiganlabs/butler/releases/tag/butler-v12.4.0), which among other things include an updated template/sample config file.

The new config file makes it easier to get started and should help with the New Relic related errors you ran into.

The idea is simply to disable as many features as possible (most were already disabled in the previous config file version, but not all). 

Some settings do need to be set, as they control how Butler connects to the Sense server. 
These settings are listed at the beginning of the template config file.
Looks like this:

```yaml
---
Butler:
  # General notes: 
  # - File and directory paths in this sample config file use Linux/Mac syntax, i.e. using forward slashes.
  #   Windows paths work just as well, just make sure to quote them with single or double quotes.
  # - All entries in the config file are mandatory in the sense that they must be present.
  #   However, if a feature is not used the corresponding config entries can contain 
  #   any value (for example the provided default ones).
  # - Butler will start using the settings in this file if the follwing settings are set first:
  #   - Butler.cert.clientCert: Set to the path of the client certificate file. If relative paths cause issues, use an absolute path.
  #   - Butler.cert.clientCertKey: Set to the path of the client key file. If relative paths cause issues, use an absolute path.
  #   - Butler.cert.clientCertCA: Set to the path of the CA certificate file. If relative paths cause issues, use an absolute path.
  #   - Butler.configEngine.host: Set to the IP or FQDN of the host where the Sense engine service is running.
  #   - Butler.configEngine.port: Set to the port where the Sense engine service is listening.
  #   - Butler.configQRS.host: Set to the IP or FQDN of the host where the Qlik Repository Service (QRS) is running.
  #   - Butler.configQRS.port: Set to the port where the Qlik Repository Service (QRS) is listening.
  # - Having set the above settings, Butler will start and run, but it will not do anything useful until you configure
  #   the various monitoring and notification settings, as described at https://butler.ptarmiganlabs.com.
  ...
  ...
```

**Comment by mountaindude** [comment]
Adding to the above, the error messages you got indicate you have _partial_ New Relic configuration settings in your Butler config file.
Removing or commenting out things like this:

Instead of this:

```yaml
  thirdPartyToolsCredentials:
    newRelic:         # Array of New Relic accounts/insert keys. Any data sent to New Relic will be sent to both accounts. 
      - accountName: First NR account
        insertApiKey: <API key 1 (with insert permissions) from New Relic> 
        accountId: <New Relic account ID 1>
      - accountName: Second NR account
        insertApiKey: <API key 2 (with insert permissions) from New Relic> 
        accountId: <New Relic account ID 2>
```

You do this:

```yaml
  thirdPartyToolsCredentials:
    newRelic:         # Array of New Relic accounts/insert keys. Any data sent to New Relic will be sent to both accounts. 
      # - accountName: First NR account
      #   insertApiKey: <API key 1 (with insert permissions) from New Relic> 
      #   accountId: <New Relic account ID 1>
      # - accountName: Second NR account
      #   insertApiKey: <API key 2 (with insert permissions) from New Relic> 
      #   accountId: <New Relic account ID 2>
```

Or simply this:

```yaml
  thirdPartyToolsCredentials:
    newRelic:         # Array of New Relic accounts/insert keys. Any data sent to New Relic will be sent to both accounts. 
```

## Example 2

And instead of this (and other places where same info is used):

```yaml
    newRelic:
      enable: false
      destinationAccount:
        event:                    # Failed/aborted reload tasks are sent as events to these New Relic accounts
          - First NR account
          - Second NR account
        log:                      # Failed/aborted reload tasks are sent as log entries to these New Relic accounts
          - First NR account
          - Second NR account
```


Do this: 

```yaml
    newRelic:
      enable: false
      destinationAccount:
        event:                    # Failed/aborted reload tasks are sent as events to these New Relic accounts
          # - First NR account
          # - Second NR account
        log:                      # Failed/aborted reload tasks are sent as log entries to these New Relic accounts
          # - First NR account
          # - Second NR account
```

You can also just remove the lines instead of commenting them out:

```yaml
    newRelic:
      enable: false
      destinationAccount:
        event:                    # Failed/aborted reload tasks are sent as events to these New Relic accounts
        log:                      # Failed/aborted reload tasks are sent as log entries to these New Relic accounts
```
