### DISCUSSION TITLE
Auto-close Signl4 incidents when reloads no longer fail

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler#1155] [Ideas]
**Is your feature request related to a problem? Please describe.**
New feature.

Could look like this in the config file:

```yaml
...
...
  incidentTool:
    signl4:
      enable: false
      url: https://connect.signl4.com/webhook/abcde12345
      reloadTaskFailure:
        ...
        autoCloseOnLaterReloadSuccess: true
      reloadTaskAborted:
        ...
        autoCloseOnLaterReloadSuccess: true
```
