### DISCUSSION TITLE
Allow/block-list of apps wrt Signl4 integration

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler#1166] [Ideas]
**Is your feature request related to a problem? Please describe.**
New feature.

Let's say Signl4 is used to track reload failures, but we want to monitor only *some* apps. 
Let the admin use whitelist/blacklist arrays or regex to define what apps should be covered by the Signl4 integration.

Could look like this in the config file:

```yaml
...
...
  incidentTool:
    signl4:
      enable: false
      url: https://connect.signl4.com/webhook/abcde12345
      reloadTaskFailure:
        enable: false
        rateLimit: 15              # Min seconds between emails for a given taskID. Defaults to 5 minutes.
        serviceName: Qlik Sense
        severity: 1
        # autoCloseOnLaterReloadSuccess: true
        includeApp:
          includeAll: false
          appId:
            - qwertyu
            - asdfghj
          appNameRegEx:
        excludeApp:
          appId:
            - zxcvbn
          appNameRegEx:
      reloadTaskAborted:
        enable: false
        rateLimit: 15              # Min seconds between emails for a given taskID. Defaults to 5 minutes.
        serviceName: Qlik Sense
        severity: 10
        # autoCloseOnLaterReloadSuccess: true
        includeApp:
          includeAll: true
          appId:
          appNameRegEx:
        excludeApp:
          appId:
          appNameRegEx:
```
