### DISCUSSION TITLE
Make it possible to add arbitrary URLs to Teams/Slack/email alerts

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler#1220] [Ideas]
Currently it is possible to add links to QMC and Hub in alert messages.
In some cases it would be useful to add other links too.
These could be defined in the Butler config file, in arrays containing link name and URL for each custom link.

As a first step a shared set of links (shared between Slack/Teams/email) could be used. 
In the future destination specific links could be added too.

**Comment by mountaindude** [comment]
Design idea
Add a section to the config file: 

```yaml
Butler:
  genericUrls:
    - id: ptarmiganlabs_com
      linkText: Ptarmigan Labs home page
      comment: The home page of the company behind Butler
      url: https://ptarmiganlabs.com
    - id: butler_docs
      linkText: Butler documentation
      comment: The documentation for Butler
      url: https://butler.ptarmiganlabs.com
```

Then make it available as a Handlebars template variable for successful/failed/aborted QSEoW reload tasks, and Windows service stopped - all with email/Slack/Teams destinations. 
And for same destinations for QS Cloud failed reloads.

It is ok that the array of URLs is empty.
