### DISCUSSION TITLE
Call webhook when reload task finish successfully

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler#1235] [Ideas]
Similar to storing info about successful reload tasks in InfluxDB (which is already supported by Butler), but call a webhook instead.

GET calls will have to embed a subset of available metadata in the URL, whereas POST and PUT calls can include more metadata in the body/payload.

Include a way to specify if webhooks should be sent for all successful reload tasks or just some. 
For example:

```yaml
Butler:
  webhookNotification: 
    reloadTaskSuccess:
      rateLimit: 15                   # Min seconds between outgoing webhook calls for a given taskID. Defaults to 5 minutes.
      webhooks:
        - description: '1a - This outgoing webhook makes a https GET and is used to ...'
          webhookURL: https://10.11.12.13:8888/butler_get_https              # outgoing webhook that Butler will call
          httpMethod: GET                   # GET/POST/PUT. Note that the body and URL query parameters differs depending on which method is used
          cert:
            enable: true                    # Set to true to use a custom CA certificate when calling the webhookURL
            rejectUnauthorized: true        # Set to false to ignore warnings/errors caused by self-signed certificates used on the webhooks server.
            certCA: /home/goran/code/secret/butler-webhook/ca-certificate.pem       # Path to the CA certificate file
          taskFilter:
            include:          # If no task names or IDs are specified below, the webhook will be called for all reload tasks 
              - name: A reload task 
              - name: Another reload task 
              - id: 86ee4ae7-7ae7-4dd4-98a1-ebea989f78fb
              - name: Yet another reload task
                id: 86ee4ae7-7ae7-4dd4-98a1-ebea989f78fb 
```
