### DISCUSSION TITLE
Store script logs on disk for failed QS Cloud reloads

### DISCUSSION THREAD

**Discussion by mountaindude** [ptarmiganlabs/butler#1265] [Ideas]
Similar to how script logs can already be stored for failed QSEoW reload tasks, it would be useful to have easy access to the logs from failed QS Cloud app reloads.

In order to be able to enable/disable this in the config file some breaking changes would be needed.
New format:

```yaml
Butler
  ...
  scriptLog:
    storeOnDisk:
      clientManaged:
        reloadTaskFailure:
          enable: true
          logDirectory: /path/to/qseow/logs
      qsCloud:
        appReloadFailure:
          enable: true
          logDirectory: /path/to/qscloud/logs
```
