### ISSUE TITLE
Streamline configuration of user activity reporting to Slack with ditto reporting for Teams

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#125]
**Is your feature request related to a problem? Please describe.**
This will be a breaking change in that the config file format changes, but the upside is that configuration of Teams, Slack and email notifications is done in a consistent way. 

Previously Slack was configured using this YAML:

```yaml
  slackConfig:
    enable: false
    webhookURL: <fill in your web hook URL from Slack>
    loginNotificationChannel: sense-user-activity     # Slack channel to which user activity data is sent
    taskFailureChannel: sense-task-failure            # Slack channel to which task failure notifications are sent
    taskAbortedChannel: sense-task-aborted            # Slack channel to which task stopped notifications are sent
```

That was fine while there was only a limited set of Slack notification options built into Butler.

With the coming notification features (i.e. using templates for Slack reload notifications) things are more complex and diverse though. Having the same config syntax for Slack, Teams and email (and possibly other future channels) would be a good thing, even if it's a breaking change.

Skip the YAML above and move it to `Butler.slackNotification.userSessionEvents` instead. 
Teams has the same config layout.
