### ISSUE TITLE
Hard coded InfluxDB tag name when storing QSEoW failed reload info?  

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#1286]
### What version of Butler are you using?

13.1.0

### What command did you use to start Butler?

-

### What operating system are you using?

-

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

-

### Describe the Bug

Seems the static tag name name below **must** be named `butler_instance`, otherwise Butler will crash when writing to InfluxDB. 

```yaml
  # InfluxDB settings
  influxDb:
    tag:
      static:                # Static tags to attach to all data stored in InflixDB
        - name: butler_instance
          value: prod
```

### Expected Behavior

Remove this requirement. No reason why one tag should be mandatory.
