### ISSUE TITLE
Add outgoing webhooks for task failure/aborts

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#129]
**Is your feature request related to a problem? Please describe.**
Webhooks are a generic, well established solution when it comes to sending notifications between systems.
It's not nearly as structured and fault tolerant as for example MQTT, but it's still useful for basic integrations.
It would make sense to have task failure/aborts available via outgoing webhooks, in addition to Slack, Teams, Email and MQTT.

**Describe the solution you'd like**
Allow for zero or more outgoing webhooks, independently configurable for task failures and task aborts.
Support various HTTP methods, PUT, POST and GET seems like a reasonable start.
It's not best practice to send outgoing calls like this using GETs, but some receiving systems may only support GETs, Or POSTs. Or PUTs. 

The parameters passed will have to be adapted to the method. 
For GETs the parameters will have to be included in the URL, i.e. query parameters.
For PUTs and POSTs the parameters should be JSON coded in the body.

The config in the YAML config file could look something like this:

```yaml
Butler:
  # Settings for notifications and messages sent using outgoing webhook
  webhookNotification:
    enable: true
    reloadTaskFailure:
      rateLimit: 300              # Min seconds between emails for a given taskID. Defaults to 5 minutes.
      webhooks:
        - description: 'This outgoing webhook is used to...'
          webhookURL: <URL>               # outgoing webhook that Butler will call
          httpMethod: POST                # GET/POST/PUT. Note that the body and URL query parameters differs depending on which method is used
        - description: 'This outgoing webhook is used to...'
          webhookURL: <URL>               # outgoing webhook that Butler will call
          httpMethod: GET                 # GET/POST/PUT. Note that the body and URL query parameters differs depending on which method is used
    reladTaskAborted:
      rateLimit: 300              # Min seconds between emails for a given taskID. Defaults to 5 minutes.
      webhooks:
        - description: 'This outgoing webhook is used to...'
          webhookURL: <URL>               # outgoing webhook that Butler will call
          httpMethod: PUT                 # GET/POST/PUT. Note that the body and URL query parameters differs depending on which method is used
        - description: 'This outgoing webhook is used to...'
          webhookURL: <URL>               # outgoing webhook that Butler will call
          httpMethod: POST                # GET/POST/PUT. Note that the body and URL query parameters differs depending on which method is used

```

A smaller set of information will be included in outgoing webhooks compared to emails/Slack/Teams notifications sent by Butler itself.  
Outgoing webhooks will include the same information as MQTT messages, i.e. the raw data received from the Sense log files. No script log etc thus.
