### ISSUE TITLE
Butler checks for custom property Butler_SuccessAlertEnableEmail even though feature is disabled

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#1308]
### What version of Butler are you using?

13.1.2

### What command did you use to start Butler?

-

### What operating system are you using?

-

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

-

### Describe the Bug

```
2024-12-03T10:26:19.099Z error: ASSERT CONFIG EMAIL: Custom property 'Butler_SuccessAlertEnableEmail' not found in Qlik Sense. Aborting.
2024-12-03T10:26:19.101Z error: MAIN: Config file does not contain required email data. Exiting.
```

But the use of a custom property for controlling sending of reload success emails is disabled in the config file, so the existence of the custom property should not be done:

```yaml
 emailNotification:
    enable: true
    reloadTaskSuccess:
      enable: true
      # Custom property used to control which task successes will cause alert emails to be sent
      # If this setting is true, alerts will not be sent for all tasks, but *only* for tasks with the CP set to the enabledValue.
      # If this setting is false, alerts will be sent for all failed reload tasks.
      alertEnableByCustomProperty:
        enable: false
        customPropertyName: 'Butler_SuccessAlertEnableEmail'
        enabledValue: 'Yes'
```
