### ISSUE TITLE
Review/improve comments in main config file settings wrt running in Docker

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#253]
For example, add info on what this setting should be when running in Docker:

```yaml
scheduler:
    enable: false
    configfile: /Users/goran/code/butler/src/config/schedule.yaml


restServerConfig:
    enable: true
    serverHost: 192.168.1.168
    serverPort: 8081
    backgroundServerPort: 8083

```
