### ISSUE TITLE
Allow regex to be used for selecting apps to be included in Signl4 integration

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#282]
**Is your feature request related to a problem? Please describe.**
New feature.

Let's say Signl4 is used to track reload failures for *some* apps. 
Let the admin use regex to define what apps should be covered by the Signl4 integration.

Could look like this in the config file:

```yaml
...
...
      reloadTaskAborted:
        enable: false
        rateLimit: 15              # Min seconds between emails for a given taskID. Defaults to 5 minutes.
        serviceName: Qlik Sense
        severity: 10
        # autoCloseOnLaterReloadSuccess: true
        includeApp:
          includeAll: true
          appId:
          appNameRegEx:
        excludeApp:
          appId:
          appNameRegEx:
```
