### ISSUE TITLE
Unhandled rejection Error: Received error code: 404::No matching endpoint found

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/butler#310]
**Describe the bug**
After upgrading from 6.0.4 to 7.0.5 error messages appears. 
All endpoints are disabled in config file.

**Screenshots**
![2021-12-09_14-39](https://user-images.githubusercontent.com/48658076/145390565-aa236eb0-450d-43e9-a013-2532fcd1b578.png)

**Describe environment:**
 - OS: Debian 10
 - Containerisation no
 - Version of Butler used 7.0.5

**Comment by mountaindude** [comment]
Thanks for the bug report. 

What version of Sense are you using?
Could you please share your Butler YAML config file? Make sure to comment out/remove sensitive info such as usernames, passwords, IP addresses (whatever you consider to be sensitive).

This will make it easier to understand what's going on and recreate the problem.

Email alerts are pretty well tested and proven to work, so it might be a config issue. 
But Butler 7.0 represents a major upgrade (almost a complete rewrite of many parts of the application!) so there may very well be new bugs that have appeared. Let's find and get rid of them if so!

**Comment by mountaindude** [comment]
@chevcheli0s that 404 error that you are getting.... It happens when Butler is trying to call the repository service's API. 
I haven't dug into it fully, but I would double your YAML config file against the current spec, available [here](https://butler.ptarmiganlabs.com/docs/reference/config-file/).

Specifically, the `Butler.configQRS` section may desire a bit extra review.
Double check that Butler can really reach the repository service's API on 10.11.12.13:4242 (using the examples from the config file below).

If you are on Linux you can do a `telnet 10.11.12.13 4242` to test connectivity to that API.

If Butler *can* reach that API and you still get that error... well then we'll need to dig deeper.

```
Butler:
...
...
  configQRS:
    authentication: certificates
    host: 10.11.12.13
    useSSL: true
    port: 4242
    headerKey: X-Qlik-User                                      # Header used to identify what user connection to QRS is made as
    headerValue: UserDirectory=Internal; UserId=sa_repository   # What user connection to QRS is made as
    rejectUnauthorized: false       # Set to false to ignore warnings/errors caused by Qlik Sense's self-signed certificates.
                                    # Set to true if the Qlik Sense root CA is available on the computer where Butler SOS is running.
```
