### ISSUE TITLE
Send uptime info to New Relic

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#398]
### Discussed in https://github.com/ptarmiganlabs/butler/discussions/396

<div type='discussions-op-text'>

<sup>Originally posted by **mountaindude** April 21, 2022</sup>
Uptime info can today be stored in InfluxDB and/or shown on screen.

While Grafana has really good looking visuals, New Relic does provide good monitoring features and is used by many corporations.
New Relic does offer a good way to monitor services like Butler (for both availability, uptime and other metrics)  and other tools in the Butler family.

Make it possible to post uptime metrics to NewRelic:

* application/json encoded body
* API key configurable in config file or via command line option
* Configurable http headers (metadata that should be passed to the monitoring service, ...)
* Configurable static fields in the payload
  * key-value pairs defined in config file
* Configurable dynamic that can be individually enabled/disabled
  * Butler memory usage
  * Butler uptime
  * 
</div>

Other features to consider:

*

**Comment by mountaindude** [comment]
# Design concept

Config file change

```yaml
...

  # Uptime monitor
  uptimeMonitor:
    enable: false                   # Should uptime messages be written to the console and log files?
    ...
    storeHttpPost:
      enable: false
      hostIP: <IP or host name>.  # Where should uptime data be sent?
      hostPort: 8765
      header:
        - name: X-Api-Key
          value: superSecretKey
        - name: X-Some-Header
          value: A fine and important value
      payload:
        static:
          - name: eventType
            value: butler-uptime-event
          - name: service
            value: butler
          - name: environment
            value: prod
        dynamic:
          butlerMemoryUsage:
            enable: true
          butlerUptime:
            enable: true
...
```
