### ISSUE TITLE
Forward script logs and other app/task metadata for failed and aborted app reloads to New Relic

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#460]
### Discussed in https://github.com/ptarmiganlabs/butler/discussions/459

<div type='discussions-op-text'>

<sup>Originally posted by **mountaindude** May 19, 2022</sup>
Reload failed alert emails, Slack and Teams messages offer a rich set of metadata related to the failed reload task/app. 

New Relic's events can handle attributes/dimensions/tags nicely, but not things like multi-line script logs.
Their "log" API can however handle multi-line log entries without problem.

New Relic events are already supported using Butler's incident tool integration.

Suggestion: 
- Add the option of sending reload failures also to the NR log API, including script logs and other data already available in alert emails/Teams/Slack. 
- Refactor the config file to make use of NR event and log APIs optional. This is unfortunately likely to be a breaking change.
</div>

**Comment by mountaindude** [comment]
New config file layout for New Relic incidents:

```yaml
...
  incidentTool:
  ...
    newRelic:
      enable: true
      # New Relic uses different API URLs for different kinds of data (metrics, events, logs, ...)
      # There are different URLs depending on whther you have an EU or US region New Relic account.
      # The available URLs are listed here: https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/choose-your-data-center/
      url:
        # As of this writing the valid options are
        # https://insights-collector.eu01.nr-data.net
        # https://insights-collector.newrelic.com 
        event: https://insights-collector.eu01.nr-data.net

        # Valid options are (1) EU/rest of world and 2) US)
        # https://log-api.eu.newrelic.com/log/v1
        # https://log-api.newrelic.com/log/v1 
        log: https://log-api.eu.newrelic.com/log/v1
      reloadTaskFailure:
        destination:
          event: 
            enable: true
            attribute: 
              static:                 # Static attributes/dimensions to attach to events sent to New Relic.
                - name: event-specific-attribute 1
                  value: abc 123
          log:
            enable: true
            tailScriptLogLines: 20
            attribute: 
              static:                 # Static attributes/dimensions to attach to events sent to New Relic.
                - name: log-specific-attribute 1
                  value: def 123
        sharedSettings:
          rateLimit: 15             # Min seconds between events sent to New Relic for a given taskID. Defaults to 5 minutes.
          header:                   # Custom http headers
            - name: X-My-Header
              value: Header value 1
          attribute: 
            static:                 # Static attributes/dimensions to attach to events sent to New Relic.
              - name: service
                value: butler
              - name: environment
                value: prod
      reloadTaskAborted:
        destination:
          event: 
            enable: true
            attribute: 
              static:                 # Static attributes/dimensions to attach to events sent to New Relic.
                - name: event-specific-attribute 2
                  value: abc 123
          log:
            enable: true
            tailScriptLogLines: 20
            attribute: 
              static:                 # Static attributes/dimensions to attach to events sent to New Relic.
                - name: log-specific-attribute 2
                  value: def 123
        sharedSettings:
          rateLimit: 15             # Min seconds between events sent to New Relic for a given taskID. Defaults to 5 minutes.
          header:                   # Custom http headers
            - name: X-My-Header
              value: Header value 2
          attribute: 
            static:                 # Static attributes/dimensions to attach to events sent to New Relic.
              - name: service
                value: butler
              - name: environment
                value: prod
```
