### ISSUE TITLE
Empty http header array for New Relic uptime storage results in run-time error

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#562]
### What version of Butler are you using?

8.5.1

### What command did you use to start Butler?

butler.exe -c D:\butler\config\butler-config.yaml --new-relic-account-name ACCOUNTNAME --new-relic-account-id ACCOUNTID --new-relic-api-key APIKEY

### What operating system are you using?

Windows, macOS

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2022 May

### Describe the Bug

If the http header section in the config file is empty, a run-time error will occur when Butler tries to store uptime info to New Relic.

```yaml
    storeNewRelic:
      enable: true
      destinationAccount:
        - SOME_ACCOUNT
      url: https://insights-collector.eu01.nr-data.net/metric/v1   # Where should uptime data be sent?
      header:                       # Custom http headers
        #- name: X-My-Header
        #  value: Header value
```

The error is:

```
error: UPTIME NEW RELIC: Error sending uptime: TypeError: globals.config.get is not a function or its return value is not iterable
```

### Expected Behavior

Should be possible to have empty arrays for http headers in the config file.
