### ISSUE TITLE
Move InfluxDB configuration to it's own part of the Butler config file

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#670]
🚨 This will be a breaking change.

## Background
Previously the only use of InfluxDB in Butler has been to store uptime and Butler memory usage information.  
With the addition of monitoring of Windows services that changes.

As there are now several parts of the Butler config file that use InfluxDB settings, those settings should be in their own `influxDb` section under the root `Butler` section in the YAML config file

## Implementation

Conceptual YAML config file:

```yaml
Butler:
  uptimeMonitor:
    storeInInfluxdb: 
      enable: true

  serviceMonitor:
    alertDestination:
      influxDb:                     # Send service alerts to InfluxDB
        enable: true

  influxDb:
    enable: true
    hostIP: 192.168.100.20
    hostPort: 8086
    auth:
      enable: false
      username: user_joe
      password: joesecret
    dbName: butler
    instanceTag: DEV              # Tag that can be used to differentiate data from multiple Butler instances
    # Default retention policy that should be created in InfluxDB when Butler creates a new database there. 
    # Any data older than retention policy threshold will be purged from InfluxDB.
    retentionPolicy:
      name: 10d
      duration: 10d   
```
