### ISSUE TITLE
Empty list of webooks in config file cause error

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler#944]
### What version of Butler are you using?

9.4.0

### What command did you use to start Butler?

node butler.js

### What operating system are you using?

macOs

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2023-Nov p3

### Describe the Bug

When there are no webhooks defined Butler will throw an `WEBHOOKOUT 1 message: webhookConfig.webhooks is not iterable` error.

```yaml
  webhookNotification:
    enable: true
    reloadTaskFailure:
      rateLimit: 15              # Min seconds between outgoing webhook calls for a given taskID. Defaults to 5 minutes.
      webhooks:
    reloadTaskAborted:
```

### Expected Behavior

Should be allowed to have empty lists of webhooks.
